name: Run tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      id: setup-python
      with:
        python-version: 3.12
    - uses: PyO3/maturin-action@v1
    - name: Run tests
      run: |
        python -m venv .venv
        . .venv/bin/activate
        maturin develop
        cargo test --all-features --verbose
